name: PumpFun Sniper Bot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # chạy mỗi 5 phút

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install telethon solana requests python-dotenv
      - name: Run bot
        run: python bot.py
